INSERT INTO gift_cards (user_id, balance, store_id, created_at, edited_at)
VALUES (1, 50, 8, default, default)
INSERT INTO gift_cards (user_id, balance, store_id, created_at, edited_at)
VALUES (2, 35.79, 2, default, default)
INSERT INTO gift_cards (user_id, balance, store_id, created_at, edited_at)
VALUES (3, 200, 7, default, default)
INSERT INTO gift_cards (user_id, balance, store_id, created_at, edited_at)
VALUES (4, 69, 1, default, default)
INSERT INTO gift_cards (user_id, balance, store_id, created_at, edited_at)
VALUES (5, 24.99, 5, default, default)
INSERT INTO gift_cards (user_id, balance, store_id, created_at, edited_at)
VALUES (6, 10.34, 3, default, default)
INSERT INTO gift_cards (user_id, balance, store_id, created_at, edited_at)
VALUES (7, 75, 4, default, default)
INSERT INTO gift_cards (user_id, balance, store_id, created_at, edited_at)
VALUES (8, 83.43, 4, default, default)
INSERT INTO gift_cards (user_id, balance, store_id, created_at, edited_at)
VALUES (9, 5.45, 10, default, default)
INSERT INTO gift_cards (user_id, balance, store_id, created_at, edited_at)
VALUES (10, 47.31, 9, default, default)
