INSERT INTO gift_cards (user_id, balance, store_id, created_at, edited_at)
VALUES (1, 50, 8, default, default)
INSERT INTO gift_cards (user_id, balance, store_id, created_at, edited_at)
VALUES (2, 35.79, 2, default, default)
INSERT INTO gift_cards (user_id, balance, store_id, created_at, edited_at)
VALUES (3, 50, 7, default, default)
INSERT INTO gift_cards (user_id, balance, store_id, created_at, edited_at)
VALUES (4, 50, 1, default, default)
INSERT INTO gift_cards (user_id, balance, store_id, created_at, edited_at)
VALUES (5, 50, 5, default, default)
INSERT INTO gift_cards (user_id, balance, store_id, created_at, edited_at)
VALUES (6, 50, 3, default, default)
INSERT INTO gift_cards (user_id, balance, store_id, created_at, edited_at)
VALUES (7, 50, 4, default, default)
INSERT INTO gift_cards (user_id, balance, store_id, created_at, edited_at)
VALUES (8, 50, 4, default, default)
INSERT INTO gift_cards (user_id, balance, store_id, created_at, edited_at)
VALUES (9, 50, 10, default, default)
INSERT INTO gift_cards (user_id, balance, store_id, created_at, edited_at)
VALUES (10, 50, 9, default, default)
