INSERT INTO TABLE loyalty_cards (user_id, store_id, description)
VALUES
(1,4,'Buy 10 Pastas get one free!')
(2,7,'Buy 10 Pastas get one free!')
(3,9,'Buy 10 Pastas get one free!')
(4,1,'Buy 10 Pastas get one free!')
(5,5,'Buy 10 Pastas get one free!')
(6,3,'Buy 10 Pastas get one free!')
(7,2,'Buy 10 Pastas get one free!')
(8,8,'Buy 10 Pastas get one free!')
(9,6,'Buy 10 Pastas get one free!')
(10,10,'Buy 10 Pastas get one free!')